######################################################################
# Automatically generated by qmake (2.01a) Do. Feb 15 23:04:59 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Network.h Solver.h Win.h
SOURCES += main.cpp Network.cpp Solver.cpp Win.cpp
